import { useParams, Link, useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useStoreAuth } from '@/contexts/StoreAuthContext';
import { useCustomDomain } from '@/contexts/CustomDomainContext';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { GroceryBottomNav } from '@/components/storefront/grocery/GroceryBottomNav';
import { useCart } from '@/hooks/useCart';
import { toast } from 'sonner';
import {
  ArrowLeft,
  Package,
  MapPin,
  LogOut,
  User,
  ChevronRight,
  Heart,
  CreditCard,
  Tag,
  Settings,
  HelpCircle,
  ChevronLeft,
  Mail,
  Pencil,
  Check,
  X,
  Loader2
} from 'lucide-react';

interface Tenant {
  id: string;
  store_name: string;
  store_slug: string;
  business_type: 'ecommerce' | 'grocery';
}

interface StoreAccountProps {
  storeName?: string;
}

// Loading skeleton for account page
const AccountSkeleton = () => (
  <div className="min-h-screen bg-neutral-50 flex flex-col">
    <div className="sticky top-0 z-40 bg-white border-b border-neutral-100 p-4">
      <div className="flex items-center gap-3">
        <div className="w-6 h-6 bg-neutral-200 rounded animate-pulse" />
        <div className="w-24 h-6 bg-neutral-200 rounded animate-pulse" />
      </div>
    </div>
    <div className="p-4 bg-white">
      <div className="flex items-center justify-between">
        <div className="space-y-2">
          <div className="w-32 h-6 bg-neutral-200 rounded animate-pulse" />
          <div className="w-24 h-4 bg-neutral-200 rounded animate-pulse" />
        </div>
        <div className="w-14 h-14 bg-neutral-200 rounded-full animate-pulse" />
      </div>
    </div>
    <div className="p-4 space-y-2">
      {[1, 2, 3, 4, 5].map(i => (
        <div key={i} className="flex items-center gap-4 p-4 bg-white rounded-lg">
          <div className="w-5 h-5 bg-neutral-200 rounded animate-pulse" />
          <div className="w-24 h-4 bg-neutral-200 rounded animate-pulse" />
        </div>
      ))}
    </div>
  </div>
);

export default function StoreAccount({ storeName }: StoreAccountProps) {
  const { slug: paramSlug } = useParams<{ slug: string }>();
  const navigate = useNavigate();
  const { customer, signOut, refreshCustomer } = useStoreAuth();
  const { tenant: cdTenant, isCustomDomain } = useCustomDomain();

  // Use slug from params or context
  const slug = isCustomDomain ? cdTenant?.store_slug : paramSlug;

  const [tenant, setTenant] = useState<Tenant | null>(null);
  const [tenantLoading, setTenantLoading] = useState(true);
  const [editingEmail, setEditingEmail] = useState(false);
  const [emailValue, setEmailValue] = useState('');
  const [savingEmail, setSavingEmail] = useState(false);

  const getLink = (path: string) => {
    if (!slug) return path;
    const cleanPath = path.startsWith('/') ? path : `/${path}`;
    return isCustomDomain ? cleanPath : `/store/${slug}${cleanPath}`;
  };

  const { itemCount } = useCart(slug || '', tenant?.id || null);

  useEffect(() => {
    const fetchTenant = async () => {
      if (isCustomDomain && cdTenant) {
        setTenant(cdTenant as Tenant);
        setTenantLoading(false);
        return;
      }

      if (!slug) {
        setTenantLoading(false);
        return;
      }
      const { data } = await supabase
        .from('tenants')
        .select('id, store_name, store_slug, business_type')
        .eq('store_slug', slug)
        .eq('is_active', true)
        .maybeSingle();
      if (data) setTenant(data as Tenant);
      setTenantLoading(false);
    };
    fetchTenant();
  }, [slug, isCustomDomain, cdTenant]);

  // Show skeleton while loading
  if (tenantLoading) return <AccountSkeleton />;

  const handleSignOut = async () => {
    await signOut();
    toast.success('Logged out successfully');
    navigate(getLink('/'));
  };

  const handleStartEditEmail = () => {
    // Extract the email - if it's auto-generated, show empty for user to enter real email
    const currentEmail = customer?.email || '';
    const isAutoGenerated = currentEmail.includes('@store.storekriti.com');
    setEmailValue(isAutoGenerated ? '' : currentEmail);
    setEditingEmail(true);
  };

  const handleCancelEditEmail = () => {
    setEditingEmail(false);
    setEmailValue('');
  };

  const handleSaveEmail = async () => {
    if (!customer) return;

    const trimmedEmail = emailValue.trim().toLowerCase();

    // Validate email format
    if (trimmedEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmedEmail)) {
      toast.error('Please enter a valid email address');
      return;
    }

    setSavingEmail(true);
    try {
      const { error } = await supabase
        .from('customers')
        .update({ email: trimmedEmail || null })
        .eq('id', customer.id);

      if (error) throw error;

      await refreshCustomer();
      toast.success('Email updated successfully');
      setEditingEmail(false);
    } catch (error: any) {
      console.error('Failed to update email:', error);
      toast.error('Failed to update email');
    } finally {
      setSavingEmail(false);
    }
  };

  // Format display email - hide auto-generated emails
  const getDisplayEmail = () => {
    const email = customer?.email || '';
    if (email.includes('@store.storekriti.com')) {
      return null; // Don't show auto-generated emails
    }
    return email;
  };

  const isGrocery = tenant?.business_type === 'grocery';

  if (!customer) {
    return (
      <div className="min-h-screen bg-white flex flex-col pb-20">
        {/* Mobile Header */}
        <div className="lg:hidden sticky top-0 z-40 bg-white border-b border-neutral-100">
          <div className="flex items-center gap-3 p-4">
            <button onClick={() => navigate(-1)} className="p-1">
              <ChevronLeft className="w-6 h-6" />
            </button>
            <h1 className="text-xl font-bold">Account</h1>
          </div>
        </div>

        <div className="flex-1 flex items-center justify-center p-4">
          <Card className="w-full max-w-md text-center">
            <CardContent className="pt-8 pb-8">
              <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-neutral-100 flex items-center justify-center">
                <User className="w-8 h-8 text-neutral-400" />
              </div>
              <h2 className="font-bold text-lg mb-2">Sign in to your account</h2>
              <p className="text-neutral-500 text-sm mb-6">Track orders, manage addresses, and more</p>
              <div className="space-y-3">
                <Link to={getLink('/login')} className="block">
                  <Button className="w-full bg-green-600 hover:bg-green-700">Sign In</Button>
                </Link>
                <Link to={getLink('/signup')} className="block">
                  <Button variant="outline" className="w-full">Create Account</Button>
                </Link>
              </div>
            </CardContent>
          </Card>
        </div>

        {isGrocery && <GroceryBottomNav storeSlug={slug || ''} cartCount={itemCount} />}
      </div>
    );
  }

  // Grocery Mobile Layout
  if (isGrocery) {
    const menuItems = [
      { icon: User, label: 'My Account', href: getLink('/account'), description: 'Profile details' },
      { icon: Package, label: 'My Orders', href: getLink('/account/orders'), description: 'Track your orders' },
      { icon: CreditCard, label: 'Payments', href: '#', description: 'Saved cards & UPI' },
      { icon: MapPin, label: 'Address', href: getLink('/account/addresses'), description: 'Saved addresses' },
      { icon: Heart, label: 'Favourites', href: getLink('/wishlist'), description: 'Your wishlist' },
      { icon: Tag, label: 'Promocodes', href: '#', description: 'Discounts & offers' },
      { icon: Settings, label: 'Settings', href: '#', description: 'App preferences' },
      { icon: HelpCircle, label: 'Help', href: '#', description: 'Support & FAQ' },
    ];

    return (
      <div className="min-h-screen bg-neutral-50 flex flex-col pb-20">
        {/* Mobile Header */}
        <div className="lg:hidden sticky top-0 z-40 bg-white border-b border-neutral-100">
          <div className="flex items-center gap-3 p-4">
            <button onClick={() => navigate(getLink('/'))} className="p-1">
              <ChevronLeft className="w-6 h-6" />
            </button>
          </div>
        </div>

        <main className="flex-1">
          {/* Profile Section */}
          <div className="bg-white p-4">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-2xl font-bold">{customer.name}</h1>
                <p className="text-neutral-500 text-sm">{customer.phone}</p>
                {editingEmail ? (
                  <div className="flex items-center gap-2 mt-2">
                    <Input
                      type="email"
                      value={emailValue}
                      onChange={(e) => setEmailValue(e.target.value)}
                      placeholder="Enter email address"
                      className="h-8 text-sm w-48"
                      autoFocus
                    />
                    <button
                      onClick={handleSaveEmail}
                      disabled={savingEmail}
                      className="p-1.5 rounded-full bg-green-100 text-green-600 hover:bg-green-200"
                    >
                      {savingEmail ? <Loader2 className="w-4 h-4 animate-spin" /> : <Check className="w-4 h-4" />}
                    </button>
                    <button
                      onClick={handleCancelEditEmail}
                      disabled={savingEmail}
                      className="p-1.5 rounded-full bg-neutral-100 text-neutral-600 hover:bg-neutral-200"
                    >
                      <X className="w-4 h-4" />
                    </button>
                  </div>
                ) : (
                  <div className="flex items-center gap-2 mt-1">
                    {getDisplayEmail() ? (
                      <p className="text-neutral-500 text-sm">{getDisplayEmail()}</p>
                    ) : (
                      <p className="text-neutral-400 text-sm italic">Add email for order updates</p>
                    )}
                    <button
                      onClick={handleStartEditEmail}
                      className="p-1 rounded-full hover:bg-neutral-100"
                    >
                      <Pencil className="w-3.5 h-3.5 text-neutral-400" />
                    </button>
                  </div>
                )}
              </div>
              <div className="w-14 h-14 rounded-full bg-neutral-100 flex items-center justify-center">
                <User className="w-7 h-7 text-neutral-400" />
              </div>
            </div>
          </div>

          {/* Membership Card */}
          <div className="p-4">
            <div className="bg-gradient-to-r from-amber-400 to-orange-400 rounded-2xl p-4 flex items-center justify-between">
              <div>
                <h3 className="font-bold text-white">Gold Membership</h3>
                <p className="text-white/80 text-sm">Free delivery on all orders</p>
                <button className="mt-2 bg-neutral-900 text-white text-xs font-semibold px-3 py-1.5 rounded-lg">
                  Know more
                </button>
              </div>
              <div className="text-4xl">🎁</div>
            </div>
          </div>

          {/* Menu Items */}
          <div className="bg-white mt-2">
            {menuItems.map((item, index) => (
              <Link
                key={item.label}
                to={item.href}
                className="flex items-center gap-4 p-4 border-b border-neutral-100 last:border-b-0"
              >
                <item.icon className="w-5 h-5 text-neutral-600" />
                <span className="flex-1 font-medium">{item.label}</span>
                <ChevronRight className="w-5 h-5 text-neutral-400" />
              </Link>
            ))}
          </div>

          {/* Sign Out */}
          <div className="p-4">
            <Button
              variant="outline"
              className="w-full border-red-200 text-red-600 hover:bg-red-50"
              onClick={handleSignOut}
            >
              <LogOut className="w-4 h-4 mr-2" />
              Sign Out
            </Button>
          </div>
        </main>

        <GroceryBottomNav storeSlug={tenant.store_slug} cartCount={itemCount} />
      </div>
    );
  }

  // E-commerce Layout (Original)
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-2xl">
        <Link to={getLink('/')} className="flex items-center gap-2 text-muted-foreground hover:text-foreground mb-6">
          <ArrowLeft className="w-4 h-4" />
          Back to store
        </Link>

        <h1 className="text-2xl font-display font-bold mb-6">My Account</h1>

        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <User className="w-5 h-5" />
                Profile
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-muted-foreground">Name</span>
                <span className="font-medium">{customer.name}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-muted-foreground">Phone</span>
                <span className="font-medium">{customer.phone || '-'}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-muted-foreground">Email</span>
                {editingEmail ? (
                  <div className="flex items-center gap-2">
                    <Input
                      type="email"
                      value={emailValue}
                      onChange={(e) => setEmailValue(e.target.value)}
                      placeholder="you@example.com"
                      className="h-8 text-sm w-48"
                      autoFocus
                    />
                    <button
                      onClick={handleSaveEmail}
                      disabled={savingEmail}
                      className="p-1.5 rounded-full bg-primary/10 text-primary hover:bg-primary/20"
                    >
                      {savingEmail ? <Loader2 className="w-4 h-4 animate-spin" /> : <Check className="w-4 h-4" />}
                    </button>
                    <button
                      onClick={handleCancelEditEmail}
                      disabled={savingEmail}
                      className="p-1.5 rounded-full bg-muted text-muted-foreground hover:bg-muted/80"
                    >
                      <X className="w-4 h-4" />
                    </button>
                  </div>
                ) : (
                  <div className="flex items-center gap-2">
                    {getDisplayEmail() ? (
                      <span className="font-medium">{getDisplayEmail()}</span>
                    ) : (
                      <span className="text-muted-foreground italic text-sm">Not set</span>
                    )}
                    <button
                      onClick={handleStartEditEmail}
                      className="p-1 rounded-full hover:bg-muted"
                    >
                      <Pencil className="w-3.5 h-3.5 text-muted-foreground" />
                    </button>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>

          <Link to={getLink('/account/orders')}>
            <Card className="hover:bg-muted/50 transition-colors cursor-pointer">
              <CardContent className="flex items-center justify-between py-4">
                <div className="flex items-center gap-3">
                  <Package className="w-5 h-5 text-primary" />
                  <span className="font-medium">My Orders</span>
                </div>
                <ArrowLeft className="w-4 h-4 rotate-180" />
              </CardContent>
            </Card>
          </Link>

          <Link to={getLink('/account/addresses')}>
            <Card className="hover:bg-muted/50 transition-colors cursor-pointer">
              <CardContent className="flex items-center justify-between py-4">
                <div className="flex items-center gap-3">
                  <MapPin className="w-5 h-5 text-primary" />
                  <span className="font-medium">Saved Addresses</span>
                </div>
                <ArrowLeft className="w-4 h-4 rotate-180" />
              </CardContent>
            </Card>
          </Link>

          <Button variant="outline" className="w-full" onClick={handleSignOut}>
            <LogOut className="w-4 h-4 mr-2" />
            Sign Out
          </Button>
        </div>
      </div>
    </div>
  );
}
